<?php

/**
 * 
 */

/**
 * Implements hook_init
 */
function devel_queries_init() {
  // Load the SQL Query Information
  global $sql_queries;
  drupal_register_shutdown_function('devel_queries_shutdown');
  if (devel_query_enabled()) {
    @include_once DRUPAL_ROOT . '/includes/database/log.inc';
    Database::startLog('devel_queries');
    ;
  }

//    dpm(count($sql_queries));
}

function devel_queries_shutdown() {
  $queries = Database::getLog('devel_queries', 'default');
//  dpm(count($queries));
  devel_queries_query_put_contents($queries);
}

// Write the variables information to the a file. It will be retrieved on demand via AJAX.
function devel_queries_query_put_contents($queries) {
  $request_id = mt_rand(1, 1000000);
  $path = "temporary://devel_queries";

  // Create the devel_querylog within the temp folder, if needed.
  file_prepare_directory($path, FILE_CREATE_DIRECTORY);

  // Occassionally wipe the querylog dir so that files don't accumulate.
  if (mt_rand(1, 1000) == 401) {
    devel_empty_dir($path);
  }

  $path .= "/$request_id.txt";
  $path = file_stream_wrapper_uri_normalize($path);
  
  file_put_contents($path, "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" , FILE_APPEND);
  file_put_contents($path, PHP_EOL, FILE_APPEND);
  file_put_contents($path, "Summary" , FILE_APPEND);
  file_put_contents($path, PHP_EOL , FILE_APPEND);
  file_put_contents($path, "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" , FILE_APPEND);
  file_put_contents($path, PHP_EOL , FILE_APPEND);
  $summary = devel_queries_get_query_summary($queries);  
  file_put_contents($path, $summary, FILE_APPEND);
  file_put_contents($path, PHP_EOL . PHP_EOL . PHP_EOL  , FILE_APPEND);
  
   
  
  file_put_contents($path, "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" , FILE_APPEND);
  file_put_contents($path, PHP_EOL , FILE_APPEND);
  file_put_contents($path, "Queries" , FILE_APPEND);
  file_put_contents($path, PHP_EOL , FILE_APPEND);
  file_put_contents($path, "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" , FILE_APPEND);
  file_put_contents($path, PHP_EOL  , FILE_APPEND);
  
  // Save queries as a json array. Suppress errors due to recursion ()
  foreach ($queries as $query) {
    $string = _get_query_string($query);
    file_put_contents($path, $string, FILE_APPEND);
    file_put_contents($path, PHP_EOL, FILE_APPEND);
  }
  file_put_contents($path, '=====================================================' , FILE_APPEND);
  file_put_contents($path, PHP_EOL . PHP_EOL . PHP_EOL , FILE_APPEND);
}

function _get_query_string($query) {
  $string = $query['query'];
  $arguments = $query['args'];

  if (!empty($arguments) && is_array($arguments)) {
    foreach ($arguments as $placeholder => &$value) {
      if (is_string($value)) {
        $value = "'$value'";
      }
    }
    $string = strtr($string, $arguments);
  }
  return $string;
}

function devel_queries_get_query_summary($queries){
  $output = '';  
  $count = count($queries);
  $output .= 'Number of queries : ' . $count;
  $output .= PHP_EOL;
  $output .= 'Url :  ' .  $_REQUEST['q'];  
  return $output;
}